name: "Build and upload the exported folder to Valist"

on:
  release:
    types: [published]

jobs:
  valist-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Checkout
        uses: actions/checkout@v3

      - name: Setup Node v16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Build and Export App
        run: |
          cd frontend
          npm install
          npm run build
          npm run export
      - name: Upload to Valist
        uses: valist-io/valist-github-action@v2.5.6
        with:
          private-key: ${{ secrets.VALIST_KEY }}
          account: yanukadeneth99
          project: wc-nft-fantasy
          release: ${{ github.event.release.tag_name }}
          path: frontend/out
